export const Role = {
  USER: "user",
  REVIEWER: "reviewer",
  DEVELOPER: "developer",
  ADMIN: "admin",
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const Permission = {
  CHAT_USE: "CHAT_USE",
  MULTIMODAL_USE: "MULTIMODAL_USE",
  CONVERSATION_READ_OWN: "CONVERSATION_READ_OWN",
  CONVERSATION_DELETE_OWN: "CONVERSATION_DELETE_OWN",
  SETTINGS_VIEW_OWN: "SETTINGS_VIEW_OWN",

  KNOWLEDGE_VIEW: "KNOWLEDGE_VIEW",
  KNOWLEDGE_REVIEW: "KNOWLEDGE_REVIEW",
  KNOWLEDGE_SOURCE_APPROVE: "KNOWLEDGE_SOURCE_APPROVE",
  KNOWLEDGE_CHUNK_APPROVE: "KNOWLEDGE_CHUNK_APPROVE",

  EVALUATION_VIEW: "EVALUATION_VIEW",
  EVALUATION_REVIEW: "EVALUATION_REVIEW",
  EVALUATION_HUMAN_SCORE: "EVALUATION_HUMAN_SCORE",
  EVALUATION_EXPORT_HUMAN_REVIEW: "EVALUATION_EXPORT_HUMAN_REVIEW",
  EVALUATION_RUN_CREATE: "EVALUATION_RUN_CREATE",
  EVALUATION_RUN_FULL: "EVALUATION_RUN_FULL",
  EVALUATION_COMPARE: "EVALUATION_COMPARE",

  AGENT_TRACE_VIEW: "AGENT_TRACE_VIEW",
  RAG_DEBUG_VIEW: "RAG_DEBUG_VIEW",
  RAG_BENCHMARK_RUN: "RAG_BENCHMARK_RUN",
  BENCHMARK_VIEW: "BENCHMARK_VIEW",
  ABLATION_RUN: "ABLATION_RUN",

  DEV_CONFIG_EDIT: "DEV_CONFIG_EDIT",
  DEV_PROMPT_EDIT: "DEV_PROMPT_EDIT",
  PRODUCTION_PROMPT_PREPARE: "PRODUCTION_PROMPT_PREPARE",
  PRODUCTION_CONFIG_EDIT: "PRODUCTION_CONFIG_EDIT",
  MODEL_SWITCH_DEVELOPMENT: "MODEL_SWITCH_DEVELOPMENT",
  MODEL_SWITCH_PRODUCTION: "MODEL_SWITCH_PRODUCTION",

  PRODUCTION_KB_PUBLISH: "PRODUCTION_KB_PUBLISH",
  PRODUCTION_KB_ROLLBACK: "PRODUCTION_KB_ROLLBACK",

  USER_MANAGE: "USER_MANAGE",
  ROLE_MANAGE: "ROLE_MANAGE",
  SECRET_STATUS_VIEW: "SECRET_STATUS_VIEW",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];

export const ROLE_LABEL: Record<Role, string> = {
  user: "USER MODE",
  reviewer: "REVIEWER MODE",
  developer: "DEVELOPER MODE",
  admin: "ADMIN MODE",
};

export function hasPermission(permissions: readonly string[], permission: Permission): boolean {
  return permissions.includes(permission);
}
